blank_issues_enabled: false
contact_links:
  - name: Get help from the community on Discord
    url: https://discord.gg/xxxxxxxxxxx
    about: Join the ytb-up Discord for community-powered support!
  - name: Matrix Bridge to the Discord server
    url: https://matrix.to/#/#ytb-up:matrix.org
    about: For those who do not want to use Discord
